services:
  - type: web
    name: obs-projesi
    runtime: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: FLASK_APP
        value: "wsgi.py"
      - key: FLASK_ENV
        value: "production"
