"""ders dagitimi modulu

Revision ID: 06ba6e6204b9
Revises: 15c6c396e7d3
Create Date: 2026-03-27 23:50:47.180070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ba6e6204b9'
down_revision = '15c6c396e7d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dersler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod', sa.String(length=20), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=False),
    sa.Column('haftalik_saat', sa.Integer(), nullable=False),
    sa.Column('sinif_seviyesi', sa.Integer(), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod')
    )
    op.create_table('ders_programlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ders_id', sa.Integer(), nullable=False),
    sa.Column('ogretmen_id', sa.Integer(), nullable=False),
    sa.Column('sube_id', sa.Integer(), nullable=False),
    sa.Column('gun', sa.String(length=20), nullable=False),
    sa.Column('ders_saati', sa.Integer(), nullable=False),
    sa.Column('donem', sa.String(length=20), nullable=False),
    sa.Column('derslik', sa.String(length=50), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ders_id'], ['dersler.id'], ),
    sa.ForeignKeyConstraint(['ogretmen_id'], ['personeller.id'], ),
    sa.ForeignKeyConstraint(['sube_id'], ['subeler.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sube_id', 'gun', 'ders_saati', 'donem', name='uq_sube_gun_saat_donem')
    )
    op.create_table('ogretmen_ders_atamalari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ogretmen_id', sa.Integer(), nullable=False),
    sa.Column('ders_id', sa.Integer(), nullable=False),
    sa.Column('sube_id', sa.Integer(), nullable=False),
    sa.Column('donem', sa.String(length=20), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ders_id'], ['dersler.id'], ),
    sa.ForeignKeyConstraint(['ogretmen_id'], ['personeller.id'], ),
    sa.ForeignKeyConstraint(['sube_id'], ['subeler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ogretmen_ders_atamalari')
    op.drop_table('ders_programlari')
    op.drop_table('dersler')
    # ### end Alembic commands ###
