"""personel_yonetimi_modeli

Revision ID: 15c6c396e7d3
Revises: bff04d0d39b2
Create Date: 2026-03-24 17:37:41.816949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c6c396e7d3'
down_revision = 'bff04d0d39b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personel_izinleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personel_id', sa.Integer(), nullable=False),
    sa.Column('izin_turu', sa.String(length=20), nullable=False),
    sa.Column('baslangic_tarihi', sa.Date(), nullable=False),
    sa.Column('bitis_tarihi', sa.Date(), nullable=False),
    sa.Column('gun_sayisi', sa.Integer(), nullable=False),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('onaylayan_id', sa.Integer(), nullable=True),
    sa.Column('olusturan_id', sa.Integer(), nullable=False),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['olusturan_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['onaylayan_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['personel_id'], ['personeller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personeller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tc_kimlik', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('cinsiyet', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('dogum_tarihi', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('telefon', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('adres', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('departman', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ise_baslama_tarihi', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('ise_bitis_tarihi', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('calisma_turu', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personeller', schema=None) as batch_op:
        batch_op.drop_column('calisma_turu')
        batch_op.drop_column('ise_bitis_tarihi')
        batch_op.drop_column('ise_baslama_tarihi')
        batch_op.drop_column('departman')
        batch_op.drop_column('adres')
        batch_op.drop_column('email')
        batch_op.drop_column('telefon')
        batch_op.drop_column('dogum_tarihi')
        batch_op.drop_column('cinsiyet')
        batch_op.drop_column('tc_kimlik')

    op.drop_table('personel_izinleri')
    # ### end Alembic commands ###
