"""duyurular modulu

Revision ID: 21026d8e7508
Revises: f88c32ce146b
Create Date: 2026-03-28 00:13:03.440923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21026d8e7508'
down_revision = 'f88c32ce146b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duyurular',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('icerik', sa.Text(), nullable=False),
    sa.Column('kategori', sa.String(length=20), nullable=False),
    sa.Column('oncelik', sa.String(length=20), nullable=False),
    sa.Column('hedef_kitle', sa.String(length=20), nullable=False),
    sa.Column('yayinlayan_id', sa.Integer(), nullable=False),
    sa.Column('yayinlanma_tarihi', sa.DateTime(), nullable=False),
    sa.Column('bitis_tarihi', sa.DateTime(), nullable=True),
    sa.Column('sabitlenmis', sa.Boolean(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('okunma_sayisi', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['yayinlayan_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etkinlikler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('tur', sa.String(length=20), nullable=False),
    sa.Column('baslangic_tarihi', sa.DateTime(), nullable=False),
    sa.Column('bitis_tarihi', sa.DateTime(), nullable=False),
    sa.Column('konum', sa.String(length=200), nullable=True),
    sa.Column('renk', sa.String(length=10), nullable=False),
    sa.Column('tum_gun', sa.Boolean(), nullable=True),
    sa.Column('olusturan_id', sa.Integer(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['olusturan_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hatirlatmalar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=False),
    sa.Column('kullanici_id', sa.Integer(), nullable=False),
    sa.Column('tamamlandi', sa.Boolean(), nullable=True),
    sa.Column('oncelik', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duyuru_okunmalari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duyuru_id', sa.Integer(), nullable=False),
    sa.Column('kullanici_id', sa.Integer(), nullable=False),
    sa.Column('okunma_tarihi', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['duyuru_id'], ['duyurular.id'], ),
    sa.ForeignKeyConstraint(['kullanici_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('duyuru_id', 'kullanici_id', name='uq_duyuru_kullanici')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('duyuru_okunmalari')
    op.drop_table('hatirlatmalar')
    op.drop_table('etkinlikler')
    op.drop_table('duyurular')
    # ### end Alembic commands ###
