"""sistem ayarlari modulu

Revision ID: 224577b22137
Revises: 31f075894e5b
Create Date: 2026-04-03 09:13:21.980893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224577b22137'
down_revision = '31f075894e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sistem_ayarlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anahtar', sa.String(length=100), nullable=False),
    sa.Column('deger', sa.Text(), nullable=True),
    sa.Column('aciklama', sa.String(length=300), nullable=True),
    sa.Column('kategori', sa.String(length=20), nullable=False),
    sa.Column('tur', sa.String(length=20), nullable=False),
    sa.Column('varsayilan', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anahtar')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sistem_ayarlari')
    # ### end Alembic commands ###
