"""kurum yonetimi modulu

Revision ID: 31f075894e5b
Revises: 4bee1f65d881
Create Date: 2026-04-03 09:08:41.813661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f075894e5b'
down_revision = '4bee1f65d881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('derslikler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=50), nullable=False),
    sa.Column('kat', sa.Integer(), nullable=True),
    sa.Column('kapasite', sa.Integer(), nullable=True),
    sa.Column('tur', sa.String(length=20), nullable=False),
    sa.Column('donanim', sa.Text(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kurumlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('kisa_ad', sa.String(length=50), nullable=True),
    sa.Column('kurum_turu', sa.String(length=20), nullable=False),
    sa.Column('kurum_kodu', sa.String(length=50), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('fax', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('web_sitesi', sa.String(length=200), nullable=True),
    sa.Column('adres', sa.Text(), nullable=True),
    sa.Column('il', sa.String(length=50), nullable=True),
    sa.Column('ilce', sa.String(length=50), nullable=True),
    sa.Column('posta_kodu', sa.String(length=10), nullable=True),
    sa.Column('vergi_dairesi', sa.String(length=100), nullable=True),
    sa.Column('vergi_no', sa.String(length=20), nullable=True),
    sa.Column('mudur_adi', sa.String(length=150), nullable=True),
    sa.Column('mudur_telefon', sa.String(length=20), nullable=True),
    sa.Column('logo_url', sa.String(length=300), nullable=True),
    sa.Column('slogan', sa.String(length=300), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ogretim_yillari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=50), nullable=False),
    sa.Column('baslangic_tarihi', sa.Date(), nullable=False),
    sa.Column('bitis_tarihi', sa.Date(), nullable=False),
    sa.Column('yariyil_baslangic', sa.Date(), nullable=True),
    sa.Column('yariyil_bitis', sa.Date(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tatiller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=150), nullable=False),
    sa.Column('baslangic_tarihi', sa.Date(), nullable=False),
    sa.Column('bitis_tarihi', sa.Date(), nullable=False),
    sa.Column('tur', sa.String(length=20), nullable=False),
    sa.Column('ogretim_yili_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ogretim_yili_id'], ['ogretim_yillari.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tatiller')
    op.drop_table('ogretim_yillari')
    op.drop_table('kurumlar')
    op.drop_table('derslikler')
    # ### end Alembic commands ###
