"""cevap anahtari ve omr tarama tablolari

Revision ID: 42f515f2d2e7
Revises: cb31d9718fa7
Create Date: 2026-04-18 20:46:54.339248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f515f2d2e7'
down_revision = 'cb31d9718fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deneme_cevap_anahtari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deneme_dersi_id', sa.Integer(), nullable=False),
    sa.Column('soru_no', sa.Integer(), nullable=False),
    sa.Column('dogru_cevap', sa.String(length=1), nullable=False),
    sa.Column('iptal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['deneme_dersi_id'], ['deneme_dersleri.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deneme_dersi_id', 'soru_no', name='uq_cevap_anahtari_ders_soru')
    )
    with op.batch_alter_table('deneme_cevap_anahtari', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deneme_cevap_anahtari_deneme_dersi_id'), ['deneme_dersi_id'], unique=False)

    op.create_table('deneme_omr_taramalari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deneme_sinavi_id', sa.Integer(), nullable=False),
    sa.Column('katilim_id', sa.Integer(), nullable=True),
    sa.Column('ogrenci_no', sa.String(length=40), nullable=True),
    sa.Column('dosya_adi', sa.String(length=255), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=False),
    sa.Column('hata_mesaji', sa.Text(), nullable=True),
    sa.Column('ham_cevaplar_json', sa.Text(), nullable=True),
    sa.Column('toplam_dogru', sa.Integer(), nullable=True),
    sa.Column('toplam_yanlis', sa.Integer(), nullable=True),
    sa.Column('toplam_bos', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deneme_sinavi_id'], ['deneme_sinavlari.id'], ),
    sa.ForeignKeyConstraint(['katilim_id'], ['deneme_katilimlari.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deneme_omr_taramalari', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deneme_omr_taramalari_deneme_sinavi_id'), ['deneme_sinavi_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deneme_omr_taramalari_katilim_id'), ['katilim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deneme_omr_taramalari_ogrenci_no'), ['ogrenci_no'], unique=False)

    # NOT: Alembic 'kullanici_modul_izinleri' ve 'sinav_katilimlari' tablolarinda
    # bagimsiz farkliliklar tespit etti; bu migration yalnizca OMR ile ilgili
    # tablolara odaklaniyor, o diffler baska bir migration'da ele alinabilir.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deneme_omr_taramalari', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deneme_omr_taramalari_ogrenci_no'))
        batch_op.drop_index(batch_op.f('ix_deneme_omr_taramalari_katilim_id'))
        batch_op.drop_index(batch_op.f('ix_deneme_omr_taramalari_deneme_sinavi_id'))

    op.drop_table('deneme_omr_taramalari')
    with op.batch_alter_table('deneme_cevap_anahtari', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deneme_cevap_anahtari_deneme_dersi_id'))

    op.drop_table('deneme_cevap_anahtari')
    # ### end Alembic commands ###
