"""kayit yonetimi tablolari ve ogrenci ek alanlari

Revision ID: 44c7c1605205
Revises: 74f804f18114
Create Date: 2026-03-23 11:29:54.028597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c7c1605205'
down_revision = '74f804f18114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kayit_donemleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=20), nullable=False),
    sa.Column('baslangic_tarihi', sa.Date(), nullable=False),
    sa.Column('bitis_tarihi', sa.Date(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad')
    )
    op.create_table('siniflar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=50), nullable=False),
    sa.Column('seviye', sa.Integer(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ogrenci_belgeleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('belge_turu', sa.String(length=50), nullable=False),
    sa.Column('teslim_edildi', sa.Boolean(), nullable=True),
    sa.Column('teslim_tarihi', sa.Date(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subeler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sinif_id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=10), nullable=False),
    sa.Column('kontenjan', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sinif_id'], ['siniflar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veli_bilgileri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('yakinlik', sa.String(length=20), nullable=False),
    sa.Column('tc_kimlik', sa.String(length=11), nullable=True),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('soyad', sa.String(length=100), nullable=False),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('meslek', sa.String(length=100), nullable=True),
    sa.Column('adres', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ogrenci_kayitlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('donem_id', sa.Integer(), nullable=False),
    sa.Column('sube_id', sa.Integer(), nullable=False),
    sa.Column('kayit_tarihi', sa.Date(), nullable=False),
    sa.Column('durum', sa.String(length=20), nullable=False),
    sa.Column('durum_tarihi', sa.Date(), nullable=True),
    sa.Column('durum_aciklama', sa.Text(), nullable=True),
    sa.Column('olusturan_id', sa.Integer(), nullable=False),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donem_id'], ['kayit_donemleri.id'], ),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.ForeignKeyConstraint(['olusturan_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sube_id'], ['subeler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ogrenciler', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tc_kimlik', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('cinsiyet', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('dogum_tarihi', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('dogum_yeri', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('telefon', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('adres', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('kan_grubu', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ogrenciler', schema=None) as batch_op:
        batch_op.drop_column('kan_grubu')
        batch_op.drop_column('adres')
        batch_op.drop_column('email')
        batch_op.drop_column('telefon')
        batch_op.drop_column('dogum_yeri')
        batch_op.drop_column('dogum_tarihi')
        batch_op.drop_column('cinsiyet')
        batch_op.drop_column('tc_kimlik')

    op.drop_table('ogrenci_kayitlari')
    op.drop_table('veli_bilgileri')
    op.drop_table('subeler')
    op.drop_table('ogrenci_belgeleri')
    op.drop_table('siniflar')
    op.drop_table('kayit_donemleri')
    # ### end Alembic commands ###
