"""online sinav modulu

Revision ID: 4bab9f70f262
Revises: 60c9cb7feed9
Create Date: 2026-04-01 15:50:06.646186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bab9f70f262'
down_revision = '60c9cb7feed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('online_sinavlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('ders_id', sa.Integer(), nullable=False),
    sa.Column('sube_id', sa.Integer(), nullable=True),
    sa.Column('olusturan_id', sa.Integer(), nullable=False),
    sa.Column('sure', sa.Integer(), nullable=False),
    sa.Column('baslangic_zamani', sa.DateTime(), nullable=False),
    sa.Column('bitis_zamani', sa.DateTime(), nullable=False),
    sa.Column('sinav_turu', sa.String(length=20), nullable=False),
    sa.Column('zorluk', sa.String(length=20), nullable=False),
    sa.Column('toplam_puan', sa.Float(), nullable=True),
    sa.Column('gecme_puani', sa.Float(), nullable=True),
    sa.Column('sorulari_karistir', sa.Boolean(), nullable=True),
    sa.Column('secenekleri_karistir', sa.Boolean(), nullable=True),
    sa.Column('sonuclari_goster', sa.Boolean(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('donem', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ders_id'], ['dersler.id'], ),
    sa.ForeignKeyConstraint(['olusturan_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sube_id'], ['subeler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sinav_katilimlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sinav_id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('baslama_zamani', sa.DateTime(), nullable=True),
    sa.Column('bitirme_zamani', sa.DateTime(), nullable=True),
    sa.Column('toplam_puan', sa.Float(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.ForeignKeyConstraint(['sinav_id'], ['online_sinavlar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sinav_id', 'ogrenci_id', name='uq_online_sinav_katilim')
    )
    op.create_table('sinav_sorulari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sinav_id', sa.Integer(), nullable=False),
    sa.Column('soru_metni', sa.Text(), nullable=False),
    sa.Column('soru_turu', sa.String(length=20), nullable=False),
    sa.Column('puan', sa.Float(), nullable=False),
    sa.Column('sira', sa.Integer(), nullable=False),
    sa.Column('zorluk', sa.String(length=20), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sinav_id'], ['online_sinavlar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('soru_secenekleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soru_id', sa.Integer(), nullable=False),
    sa.Column('secenek_metni', sa.Text(), nullable=False),
    sa.Column('sira', sa.Integer(), nullable=False),
    sa.Column('dogru_mu', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['soru_id'], ['sinav_sorulari.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ogrenci_cevaplari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('katilim_id', sa.Integer(), nullable=False),
    sa.Column('soru_id', sa.Integer(), nullable=False),
    sa.Column('cevap_metni', sa.Text(), nullable=True),
    sa.Column('secilen_secenek_id', sa.Integer(), nullable=True),
    sa.Column('dogru_yanlis_cevap', sa.Boolean(), nullable=True),
    sa.Column('puan', sa.Float(), nullable=True),
    sa.Column('dogru_mu', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['katilim_id'], ['sinav_katilimlari.id'], ),
    sa.ForeignKeyConstraint(['secilen_secenek_id'], ['soru_secenekleri.id'], ),
    sa.ForeignKeyConstraint(['soru_id'], ['sinav_sorulari.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ogrenci_cevaplari')
    op.drop_table('soru_secenekleri')
    op.drop_table('sinav_sorulari')
    op.drop_table('sinav_katilimlari')
    op.drop_table('online_sinavlar')
    # ### end Alembic commands ###
