"""kulupler modulu

Revision ID: 4bee1f65d881
Revises: 4bab9f70f262
Create Date: 2026-04-01 23:53:59.391619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bee1f65d881'
down_revision = '4bab9f70f262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kulupler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('kategori', sa.String(length=20), nullable=False),
    sa.Column('danisman_id', sa.Integer(), nullable=True),
    sa.Column('kontenjan', sa.Integer(), nullable=True),
    sa.Column('toplanti_gunu', sa.String(length=20), nullable=True),
    sa.Column('toplanti_saati', sa.String(length=20), nullable=True),
    sa.Column('toplanti_yeri', sa.String(length=200), nullable=True),
    sa.Column('donem', sa.String(length=20), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['danisman_id'], ['personeller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kulup_etkinlikleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kulup_id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=False),
    sa.Column('konum', sa.String(length=200), nullable=True),
    sa.Column('tur', sa.String(length=20), nullable=False),
    sa.Column('durum', sa.String(length=20), nullable=False),
    sa.Column('olusturan_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kulup_id'], ['kulupler.id'], ),
    sa.ForeignKeyConstraint(['olusturan_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kulup_uyelikleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kulup_id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('katilim_tarihi', sa.Date(), nullable=True),
    sa.Column('gorev', sa.String(length=30), nullable=False),
    sa.Column('durum', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kulup_id'], ['kulupler.id'], ),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kulup_id', 'ogrenci_id', name='uq_kulup_ogrenci')
    )
    op.create_table('kulup_devamsizliklari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etkinlik_id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('durum', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['etkinlik_id'], ['kulup_etkinlikleri.id'], ),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etkinlik_id', 'ogrenci_id', name='uq_etkinlik_ogrenci')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kulup_devamsizliklari')
    op.drop_table('kulup_uyelikleri')
    op.drop_table('kulup_etkinlikleri')
    op.drop_table('kulupler')
    # ### end Alembic commands ###
