"""iletisim modulu

Revision ID: 60c9cb7feed9
Revises: 9fd0c8d38ffc
Create Date: 2026-03-29 10:08:42.212600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60c9cb7feed9'
down_revision = '9fd0c8d38ffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iletisim_defteri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('soyad', sa.String(length=100), nullable=False),
    sa.Column('telefon', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('kurum', sa.String(length=200), nullable=True),
    sa.Column('gorev', sa.String(length=200), nullable=True),
    sa.Column('kategori', sa.String(length=20), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=True),
    sa.Column('yakinlik', sa.String(length=20), nullable=True),
    sa.Column('olusturan_id', sa.Integer(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.ForeignKeyConstraint(['olusturan_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mesaj_sablonlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('icerik', sa.Text(), nullable=False),
    sa.Column('kategori', sa.String(length=20), nullable=False),
    sa.Column('olusturan_id', sa.Integer(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['olusturan_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mesajlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gonderen_id', sa.Integer(), nullable=False),
    sa.Column('alici_id', sa.Integer(), nullable=False),
    sa.Column('konu', sa.String(length=200), nullable=False),
    sa.Column('icerik', sa.Text(), nullable=False),
    sa.Column('okundu', sa.Boolean(), nullable=True),
    sa.Column('okunma_tarihi', sa.DateTime(), nullable=True),
    sa.Column('onemli', sa.Boolean(), nullable=True),
    sa.Column('silindi_gonderen', sa.Boolean(), nullable=True),
    sa.Column('silindi_alici', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alici_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['gonderen_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toplu_mesajlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gonderen_id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('icerik', sa.Text(), nullable=False),
    sa.Column('hedef_grup', sa.String(length=20), nullable=False),
    sa.Column('hedef_sinif', sa.String(length=20), nullable=True),
    sa.Column('gonderim_tarihi', sa.DateTime(), nullable=True),
    sa.Column('gonderim_turu', sa.String(length=20), nullable=False),
    sa.Column('toplam_alici', sa.Integer(), nullable=True),
    sa.Column('basarili_gonderim', sa.Integer(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gonderen_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toplu_mesaj_alicilari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('toplu_mesaj_id', sa.Integer(), nullable=False),
    sa.Column('alici_adi', sa.String(length=200), nullable=False),
    sa.Column('alici_iletisim', sa.String(length=200), nullable=False),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('hata_mesaji', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['toplu_mesaj_id'], ['toplu_mesajlar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toplu_mesaj_alicilari')
    op.drop_table('toplu_mesajlar')
    op.drop_table('mesajlar')
    op.drop_table('mesaj_sablonlari')
    op.drop_table('iletisim_defteri')
    # ### end Alembic commands ###
