"""ilk migration - kullanici ve muhasebe tablolari

Revision ID: 74f804f18114
Revises: 
Create Date: 2026-03-23 11:17:45.287100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f804f18114'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banka_hesaplari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banka_adi', sa.String(length=100), nullable=False),
    sa.Column('hesap_adi', sa.String(length=100), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('hesap_no', sa.String(length=30), nullable=True),
    sa.Column('bakiye', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('para_birimi', sa.String(length=5), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gelir_gider_kategorileri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('tur', sa.String(length=10), nullable=False),
    sa.Column('ust_kategori_id', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ust_kategori_id'], ['gelir_gider_kategorileri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ogrenciler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_no', sa.String(length=20), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('soyad', sa.String(length=100), nullable=False),
    sa.Column('sinif', sa.String(length=20), nullable=True),
    sa.Column('veli_ad', sa.String(length=100), nullable=True),
    sa.Column('veli_telefon', sa.String(length=20), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('kayit_tarihi', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ogrenci_no')
    )
    op.create_table('personeller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sicil_no', sa.String(length=20), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('soyad', sa.String(length=100), nullable=False),
    sa.Column('pozisyon', sa.String(length=100), nullable=True),
    sa.Column('maas', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sicil_no')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('soyad', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('banka_hareketleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banka_hesap_id', sa.Integer(), nullable=False),
    sa.Column('tur', sa.String(length=10), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('karsi_hesap_id', sa.Integer(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['banka_hesap_id'], ['banka_hesaplari.id'], ),
    sa.ForeignKeyConstraint(['karsi_hesap_id'], ['banka_hesaplari.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gelir_gider_kayitlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kategori_id', sa.Integer(), nullable=False),
    sa.Column('tur', sa.String(length=10), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('belge_no', sa.String(length=50), nullable=True),
    sa.Column('banka_hesap_id', sa.Integer(), nullable=True),
    sa.Column('olusturan_id', sa.Integer(), nullable=False),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['banka_hesap_id'], ['banka_hesaplari.id'], ),
    sa.ForeignKeyConstraint(['kategori_id'], ['gelir_gider_kategorileri.id'], ),
    sa.ForeignKeyConstraint(['olusturan_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odeme_planlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('donem', sa.String(length=20), nullable=False),
    sa.Column('toplam_tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('taksit_sayisi', sa.Integer(), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personel_odeme_kayitlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personel_id', sa.Integer(), nullable=False),
    sa.Column('donem', sa.String(length=20), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('odeme_turu', sa.String(length=20), nullable=False),
    sa.Column('banka_hesap_id', sa.Integer(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('olusturan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['banka_hesap_id'], ['banka_hesaplari.id'], ),
    sa.ForeignKeyConstraint(['olusturan_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['personel_id'], ['personeller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taksitler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odeme_plani_id', sa.Integer(), nullable=False),
    sa.Column('taksit_no', sa.Integer(), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vade_tarihi', sa.Date(), nullable=False),
    sa.Column('odenen_tutar', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('odeme_tarihi', sa.Date(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['odeme_plani_id'], ['odeme_planlari.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odemeler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taksit_id', sa.Integer(), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('odeme_turu', sa.String(length=20), nullable=False),
    sa.Column('banka_hesap_id', sa.Integer(), nullable=True),
    sa.Column('makbuz_no', sa.String(length=50), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=False),
    sa.Column('olusturan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['banka_hesap_id'], ['banka_hesaplari.id'], ),
    sa.ForeignKeyConstraint(['olusturan_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['taksit_id'], ['taksitler.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('makbuz_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('odemeler')
    op.drop_table('taksitler')
    op.drop_table('personel_odeme_kayitlari')
    op.drop_table('odeme_planlari')
    op.drop_table('gelir_gider_kayitlari')
    op.drop_table('banka_hareketleri')
    op.drop_table('users')
    op.drop_table('personeller')
    op.drop_table('ogrenciler')
    op.drop_table('gelir_gider_kategorileri')
    op.drop_table('banka_hesaplari')
    # ### end Alembic commands ###
