"""rehberlik modulu

Revision ID: 9e90fc337fb6
Revises: 21026d8e7508
Create Date: 2026-03-28 09:57:14.845064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e90fc337fb6'
down_revision = '21026d8e7508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('davranis_kayitlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('kaydeden_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('tur', sa.String(length=20), nullable=False),
    sa.Column('kategori', sa.String(length=20), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=False),
    sa.Column('alinan_onlem', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kaydeden_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rehberlik_gorusmeleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('rehber_id', sa.Integer(), nullable=False),
    sa.Column('gorusme_tarihi', sa.DateTime(), nullable=False),
    sa.Column('gorusme_turu', sa.String(length=20), nullable=False),
    sa.Column('konu', sa.String(length=200), nullable=False),
    sa.Column('icerik', sa.Text(), nullable=True),
    sa.Column('sonuc_ve_oneri', sa.Text(), nullable=True),
    sa.Column('gizlilik_seviyesi', sa.String(length=20), nullable=False),
    sa.Column('durum', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.ForeignKeyConstraint(['rehber_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rehberlik_planlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('rehber_id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('hedefler', sa.Text(), nullable=True),
    sa.Column('uygulanacak_yontemler', sa.Text(), nullable=True),
    sa.Column('baslangic_tarihi', sa.Date(), nullable=False),
    sa.Column('bitis_tarihi', sa.Date(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=False),
    sa.Column('degerlendirme', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.ForeignKeyConstraint(['rehber_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rehberlik_profilleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('aile_durumu', sa.String(length=20), nullable=False),
    sa.Column('kardes_sayisi', sa.Integer(), nullable=True),
    sa.Column('ekonomik_durum', sa.String(length=20), nullable=True),
    sa.Column('saglik_durumu', sa.Text(), nullable=True),
    sa.Column('ozel_not', sa.Text(), nullable=True),
    sa.Column('ilgi_alanlari', sa.Text(), nullable=True),
    sa.Column('guclu_yonler', sa.Text(), nullable=True),
    sa.Column('gelistirilecek_yonler', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ogrenci_id')
    )
    op.create_table('veli_gorusmeleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('veli_adi', sa.String(length=200), nullable=False),
    sa.Column('veli_telefon', sa.String(length=20), nullable=True),
    sa.Column('gorusme_tarihi', sa.DateTime(), nullable=False),
    sa.Column('gorusme_turu', sa.String(length=20), nullable=False),
    sa.Column('konu', sa.String(length=200), nullable=False),
    sa.Column('icerik', sa.Text(), nullable=True),
    sa.Column('sonuc', sa.Text(), nullable=True),
    sa.Column('gorusen_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gorusen_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('veli_gorusmeleri')
    op.drop_table('rehberlik_profilleri')
    op.drop_table('rehberlik_planlari')
    op.drop_table('rehberlik_gorusmeleri')
    op.drop_table('davranis_kayitlari')
    # ### end Alembic commands ###
