"""saglik modulu

Revision ID: 9fd0c8d38ffc
Revises: 9e90fc337fb6
Create Date: 2026-03-28 10:10:25.529904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd0c8d38ffc'
down_revision = '9e90fc337fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asi_takip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('asi_adi', sa.String(length=100), nullable=False),
    sa.Column('asi_tarihi', sa.Date(), nullable=False),
    sa.Column('hatirlatma_tarihi', sa.Date(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revir_kayitlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.DateTime(), nullable=False),
    sa.Column('sikayet', sa.Text(), nullable=False),
    sa.Column('yapilan_islem', sa.Text(), nullable=False),
    sa.Column('verilen_ilac', sa.String(length=200), nullable=True),
    sa.Column('sonuc', sa.String(length=30), nullable=False),
    sa.Column('ilgilenen_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ilgilenen_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saglik_kayitlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('kan_grubu', sa.String(length=5), nullable=True),
    sa.Column('boy', sa.Float(), nullable=True),
    sa.Column('kilo', sa.Float(), nullable=True),
    sa.Column('kronik_hastalik', sa.Text(), nullable=True),
    sa.Column('alerji', sa.Text(), nullable=True),
    sa.Column('surekli_ilac', sa.Text(), nullable=True),
    sa.Column('engel_durumu', sa.String(length=20), nullable=False),
    sa.Column('ozel_not', sa.Text(), nullable=True),
    sa.Column('acil_kisi_adi', sa.String(length=100), nullable=True),
    sa.Column('acil_kisi_telefon', sa.String(length=20), nullable=True),
    sa.Column('acil_kisi_yakinlik', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ogrenci_id')
    )
    op.create_table('saglik_taramalari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('tarama_tarihi', sa.Date(), nullable=False),
    sa.Column('tarama_turu', sa.String(length=20), nullable=False),
    sa.Column('sonuc', sa.String(length=20), nullable=False),
    sa.Column('bulgular', sa.Text(), nullable=False),
    sa.Column('oneri', sa.Text(), nullable=True),
    sa.Column('tarayan_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.ForeignKeyConstraint(['tarayan_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saglik_taramalari')
    op.drop_table('saglik_kayitlari')
    op.drop_table('revir_kayitlari')
    op.drop_table('asi_takip')
    # ### end Alembic commands ###
