"""etut yonetimi modulu

Revision ID: a3d7e9c1f4b2
Revises: c5aa19a42858
Create Date: 2026-04-04 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d7e9c1f4b2'
down_revision = 'c5aa19a42858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etutler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('ders_id', sa.Integer(), nullable=True),
    sa.Column('ogretmen_id', sa.Integer(), nullable=False),
    sa.Column('sube_id', sa.Integer(), nullable=True),
    sa.Column('gun', sa.String(length=20), nullable=False),
    sa.Column('baslangic_saati', sa.Time(), nullable=False),
    sa.Column('bitis_saati', sa.Time(), nullable=False),
    sa.Column('derslik', sa.String(length=50), nullable=True),
    sa.Column('kontenjan', sa.Integer(), nullable=False),
    sa.Column('donem', sa.String(length=20), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ders_id'], ['dersler.id'], ),
    sa.ForeignKeyConstraint(['ogretmen_id'], ['personeller.id'], ),
    sa.ForeignKeyConstraint(['sube_id'], ['subeler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etut_katilimlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etut_id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('katildi', sa.Boolean(), nullable=True),
    sa.Column('aciklama', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['etut_id'], ['etutler.id'], ),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etut_katilimlari')
    op.drop_table('etutler')
    # ### end Alembic commands ###
