"""Add Devamsizlik model

Revision ID: bff04d0d39b2
Revises: 44c7c1605205
Create Date: 2026-03-23 15:41:08.311499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff04d0d39b2'
down_revision = '44c7c1605205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devamsizlik_kayitlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('sube_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('ders_saati', sa.Integer(), nullable=False),
    sa.Column('durum', sa.String(length=20), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('olusturan_id', sa.Integer(), nullable=False),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.ForeignKeyConstraint(['olusturan_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sube_id'], ['subeler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devamsizlik_kayitlari')
    # ### end Alembic commands ###
