"""bildirim sistemi

Revision ID: c5aa19a42858
Revises: 224577b22137
Create Date: 2026-04-04 00:11:18.818433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5aa19a42858'
down_revision = '224577b22137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bildirimler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kullanici_id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('mesaj', sa.Text(), nullable=False),
    sa.Column('tur', sa.String(length=20), nullable=False),
    sa.Column('kategori', sa.String(length=20), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('okundu', sa.Boolean(), nullable=True),
    sa.Column('okunma_tarihi', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bildirimler')
    # ### end Alembic commands ###
