"""deneme_sinavi modulu: DenemeSinavi, DenemeDersi, DenemeKatilim, DenemeDersSonucu

Revision ID: cb31d9718fa7
Revises: ed312251aef5
Create Date: 2026-04-18 14:14:30.378356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb31d9718fa7'
down_revision = 'ed312251aef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deneme_sinavlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('sinav_tipi', sa.String(length=20), nullable=False),
    sa.Column('donem', sa.String(length=20), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('hedef_seviye', sa.String(length=20), nullable=True),
    sa.Column('sure_dakika', sa.Integer(), nullable=False),
    sa.Column('durum', sa.String(length=20), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('olusturan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['olusturan_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deneme_sinavlari', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deneme_sinavlari_durum'), ['durum'], unique=False)
        batch_op.create_index(batch_op.f('ix_deneme_sinavlari_sinav_tipi'), ['sinav_tipi'], unique=False)

    op.create_table('deneme_dersleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deneme_sinavi_id', sa.Integer(), nullable=False),
    sa.Column('ders_kodu', sa.String(length=40), nullable=False),
    sa.Column('ders_adi', sa.String(length=100), nullable=False),
    sa.Column('soru_sayisi', sa.Integer(), nullable=False),
    sa.Column('sira', sa.Integer(), nullable=False),
    sa.Column('katsayi', sa.Float(), nullable=True),
    sa.Column('alan', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['deneme_sinavi_id'], ['deneme_sinavlari.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deneme_dersleri', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deneme_dersleri_deneme_sinavi_id'), ['deneme_sinavi_id'], unique=False)

    op.create_table('deneme_katilimlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deneme_sinavi_id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('sube_id', sa.Integer(), nullable=True),
    sa.Column('katildi', sa.Boolean(), nullable=False),
    sa.Column('obp', sa.Float(), nullable=True),
    sa.Column('toplam_dogru', sa.Integer(), nullable=True),
    sa.Column('toplam_yanlis', sa.Integer(), nullable=True),
    sa.Column('toplam_bos', sa.Integer(), nullable=True),
    sa.Column('toplam_net', sa.Float(), nullable=True),
    sa.Column('toplam_puan', sa.Float(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deneme_sinavi_id'], ['deneme_sinavlari.id'], ),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.ForeignKeyConstraint(['sube_id'], ['subeler.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deneme_sinavi_id', 'ogrenci_id', name='uq_deneme_katilim_ogrenci')
    )
    with op.batch_alter_table('deneme_katilimlari', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deneme_katilimlari_deneme_sinavi_id'), ['deneme_sinavi_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deneme_katilimlari_ogrenci_id'), ['ogrenci_id'], unique=False)

    op.create_table('deneme_ders_sonuclari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('katilim_id', sa.Integer(), nullable=False),
    sa.Column('deneme_dersi_id', sa.Integer(), nullable=False),
    sa.Column('dogru', sa.Integer(), nullable=False),
    sa.Column('yanlis', sa.Integer(), nullable=False),
    sa.Column('bos', sa.Integer(), nullable=False),
    sa.Column('net', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['deneme_dersi_id'], ['deneme_dersleri.id'], ),
    sa.ForeignKeyConstraint(['katilim_id'], ['deneme_katilimlari.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('katilim_id', 'deneme_dersi_id', name='uq_deneme_ders_sonucu')
    )
    with op.batch_alter_table('deneme_ders_sonuclari', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deneme_ders_sonuclari_deneme_dersi_id'), ['deneme_dersi_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deneme_ders_sonuclari_katilim_id'), ['katilim_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deneme_ders_sonuclari', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deneme_ders_sonuclari_katilim_id'))
        batch_op.drop_index(batch_op.f('ix_deneme_ders_sonuclari_deneme_dersi_id'))

    op.drop_table('deneme_ders_sonuclari')
    with op.batch_alter_table('deneme_katilimlari', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deneme_katilimlari_ogrenci_id'))
        batch_op.drop_index(batch_op.f('ix_deneme_katilimlari_deneme_sinavi_id'))

    op.drop_table('deneme_katilimlari')
    with op.batch_alter_table('deneme_dersleri', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deneme_dersleri_deneme_sinavi_id'))

    op.drop_table('deneme_dersleri')
    with op.batch_alter_table('deneme_sinavlari', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deneme_sinavlari_sinav_tipi'))
        batch_op.drop_index(batch_op.f('ix_deneme_sinavlari_durum'))

    op.drop_table('deneme_sinavlari')
    # ### end Alembic commands ###
