"""not defteri modulu

Revision ID: f88c32ce146b
Revises: 06ba6e6204b9
Create Date: 2026-03-28 00:02:50.381516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f88c32ce146b'
down_revision = '06ba6e6204b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sinav_turleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=50), nullable=False),
    sa.Column('tur', sa.String(length=20), nullable=False),
    sa.Column('agirlik', sa.Float(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odev_takip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ders_id', sa.Integer(), nullable=False),
    sa.Column('sube_id', sa.Integer(), nullable=False),
    sa.Column('ogretmen_id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('son_teslim_tarihi', sa.Date(), nullable=False),
    sa.Column('donem', sa.String(length=20), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ders_id'], ['dersler.id'], ),
    sa.ForeignKeyConstraint(['ogretmen_id'], ['personeller.id'], ),
    sa.ForeignKeyConstraint(['sube_id'], ['subeler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sinavlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('sinav_turu_id', sa.Integer(), nullable=False),
    sa.Column('ders_id', sa.Integer(), nullable=False),
    sa.Column('sube_id', sa.Integer(), nullable=False),
    sa.Column('ogretmen_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('donem', sa.String(length=20), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ders_id'], ['dersler.id'], ),
    sa.ForeignKeyConstraint(['ogretmen_id'], ['personeller.id'], ),
    sa.ForeignKeyConstraint(['sinav_turu_id'], ['sinav_turleri.id'], ),
    sa.ForeignKeyConstraint(['sube_id'], ['subeler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odev_teslimleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odev_id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('teslim_tarihi', sa.Date(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=False),
    sa.Column('puan', sa.Float(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['odev_id'], ['odev_takip.id'], ),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ogrenci_notlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sinav_id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('puan', sa.Float(), nullable=True),
    sa.Column('harf_notu', sa.String(length=5), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.ForeignKeyConstraint(['sinav_id'], ['sinavlar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sinav_id', 'ogrenci_id', name='uq_sinav_ogrenci')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ogrenci_notlari')
    op.drop_table('odev_teslimleri')
    op.drop_table('sinavlar')
    op.drop_table('odev_takip')
    op.drop_table('sinav_turleri')
    # ### end Alembic commands ###
